# Generated by Django 4.0.5 on 2022-06-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='regions/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Регіон',
                'verbose_name_plural': 'Регіони',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='сountries/', verbose_name='Зображення')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
            options={
                'verbose_name': 'Держава',
                'verbose_name_plural': 'Держави',
            },
        ),
    ]
