# Generated by Django 4.0.5 on 2022-06-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='attractions/', verbose_name='Зображення')),
                ('description', models.TextField(verbose_name='Опис')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country')),
            ],
            options={
                'verbose_name': "Пам'ятка",
                'verbose_name_plural': "Пам'ятки",
            },
        ),
    ]
