# Generated by Django 4.0.5 on 2022-06-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0007_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник коментаря'),
        ),
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Контроль'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_attractions', to='attractions.attractions'),
        ),
    ]
