# Generated by Django 4.0.5 on 2022-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_remove_comments_date_added_remove_comments_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='status',
        ),
    ]
