# Generated by Django 4.0.5 on 2022-06-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0009_remove_comments_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
    ]
