# Generated by Django 4.0.5 on 2022-06-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0010_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='attractions.attractions'),
        ),
    ]
