# Generated by Django 4.0.5 on 2022-06-17 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0014_remove_attractions_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='likes',
            field=models.ManyToManyField(related_name='like_attractions', to=settings.AUTH_USER_MODEL),
        ),
    ]
