# Generated by Django 4.0.5 on 2022-06-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0016_alter_attractions_likes_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
