# Generated by Django 4.0.5 on 2022-06-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0017_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='likes',
        ),
    ]
